ALTER TABLE menu_items
    ADD CONSTRAINT pk_menu_items PRIMARY KEY (id);

CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    store_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT fk_carts_owner
        FOREIGN KEY (owner_id)
            REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_carts_store
        FOREIGN KEY (store_id)
            REFERENCES stores (id)
            ON DELETE CASCADE,
    CONSTRAINT uc_carts_owner_store UNIQUE (owner_id, store_id)
);

CREATE INDEX idx_carts_owner_id ON carts (owner_id);

CREATE TABLE cart_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id        BIGINT                                  NOT NULL,
    menu_item_id   BIGINT                                  NOT NULL,
    configurations JSONB                                   NOT NULL DEFAULT '[]',
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_menu_item
        FOREIGN KEY (menu_item_id)
            REFERENCES menu_items (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
