CREATE TABLE menu_item_configurations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_item_id BIGINT                                  NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    type         VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_menu_item_configurations PRIMARY KEY (id),
    CONSTRAINT fk_menu_item_configurations_menu_item
        FOREIGN KEY (menu_item_id)
            REFERENCES menu_items (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_menu_item_configurations_menu_item_id
    ON menu_item_configurations (menu_item_id);

CREATE TABLE menu_item_configuration_options
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menu_item_configuration_id  BIGINT                                  NOT NULL,
    name                        VARCHAR(255)                            NOT NULL,
    additional_price            NUMERIC(10, 2)                          NOT NULL,
    CONSTRAINT pk_menu_item_configuration_options PRIMARY KEY (id),
    CONSTRAINT fk_menu_item_configuration_options_configuration
        FOREIGN KEY (menu_item_configuration_id)
            REFERENCES menu_item_configurations (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_menu_item_configuration_options_configuration_id
    ON menu_item_configuration_options (menu_item_configuration_id);

CREATE TABLE cart_item_configurations
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_item_id                      BIGINT                                  NOT NULL,
    menu_item_configuration_option_id BIGINT                                  NOT NULL,
    quantity                          INTEGER                                 NOT NULL DEFAULT 1,
    CONSTRAINT pk_cart_item_configurations PRIMARY KEY (id),
    CONSTRAINT fk_cart_item_configurations_cart_item
        FOREIGN KEY (cart_item_id)
            REFERENCES cart_items (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_configurations_option
        FOREIGN KEY (menu_item_configuration_option_id)
            REFERENCES menu_item_configuration_options (id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_cart_item_configurations_cart_item_id
    ON cart_item_configurations (cart_item_id);

ALTER TABLE menu_items
    DROP COLUMN configurations;

ALTER TABLE cart_items
    DROP COLUMN configurations;
