CREATE TABLE orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               BIGINT                                  NOT NULL,
    store_id              BIGINT                                  NOT NULL,
    cart_id               BIGINT                                  NOT NULL,
    address_id            BIGINT                                  NOT NULL,
    delivery_address_line VARCHAR(512)                            NOT NULL,
    delivery_fee          NUMERIC(10, 2)                          NOT NULL,
    total_price           NUMERIC(10, 2)                          NOT NULL,
    status                VARCHAR(32)                             NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);

CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    menu_item_id BIGINT                                  NOT NULL,
    category     VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    price        NUMERIC(10, 2)                          NOT NULL,
    notes        VARCHAR(240),
    ingredients  TEXT,
    image_id     BIGINT,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);

CREATE TABLE order_item_configurations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_id BIGINT                                  NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_order_item_configurations PRIMARY KEY (id),
    CONSTRAINT fk_order_item_configurations_order_item
        FOREIGN KEY (order_item_id)
            REFERENCES order_items (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_order_item_configurations_order_item_id
    ON order_item_configurations (order_item_id);

CREATE TABLE order_item_configuration_options
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_configuration_id BIGINT                                  NOT NULL,
    name                        VARCHAR(255)                            NOT NULL,
    additional_price            NUMERIC(10, 2)                          NOT NULL,
    quantity                    INTEGER                                 NOT NULL DEFAULT 1,
    CONSTRAINT pk_order_item_configuration_options PRIMARY KEY (id),
    CONSTRAINT fk_order_item_configuration_options_configuration
        FOREIGN KEY (order_item_configuration_id)
            REFERENCES order_item_configurations (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_order_item_configuration_options_configuration_id
    ON order_item_configuration_options (order_item_configuration_id);
