CREATE SEQUENCE IF NOT EXISTS images_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category      VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    mime_type     VARCHAR(255)                            NOT NULL,
    original_name VARCHAR(255)                            NOT NULL,
    owner_user_id BIGINT                                  NOT NULL,
    size_in_bytes BIGINT                                  NOT NULL,
    stored_name   VARCHAR(255)                            NOT NULL,
    CONSTRAINT images_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD profile_image_id BIGINT;

ALTER TABLE refresh_tokens
    ALTER
        COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING (created_at::TIMESTAMP WITHOUT TIME ZONE);

ALTER TABLE users
    ALTER
        COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING (created_at::TIMESTAMP WITHOUT TIME ZONE);

ALTER TABLE refresh_tokens
    ALTER
        COLUMN expires_at TYPE TIMESTAMP WITHOUT TIME ZONE USING (expires_at::TIMESTAMP WITHOUT TIME ZONE);