CREATE SEQUENCE IF NOT EXISTS categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS stores_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE stores
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    logo_image_id  BIGINT,
    cover_image_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

CREATE TABLE stores_categories
(
    store_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT stores_categories_pkey PRIMARY KEY (store_id, category_id)
);

ALTER TABLE stores_categories
    ADD CONSTRAINT stores_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE stores_categories
    ADD CONSTRAINT stores_categories_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE NO ACTION;