ALTER TABLE stores
    ALTER COLUMN owner_user_id SET NOT NULL;

-- Enable PostGIS (safe if already enabled)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Create addresses table
CREATE TABLE addresses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zip_code      VARCHAR(20)                             NOT NULL,
    street        VARCHAR(255)                            NOT NULL,
    number        VARCHAR(50),
    complement    VARCHAR(255),
    location      geometry(Point, 4326)                   NOT NULL,
    owner_user_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- Create spatial index (important for performance)
CREATE INDEX idx_addresses_location
    ON addresses
        USING GIST (location);