-- Create table
CREATE TABLE menu_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_id       BIGINT                                  NOT NULL,
    category       VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    price          NUMERIC(10, 2)                          NOT NULL,

    ingredients    TEXT,

    configurations JSONB                                   NOT NULL DEFAULT '[]',

    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    -- Foreign key
    CONSTRAINT fk_menu_items_store
        FOREIGN KEY (store_id)
            REFERENCES stores (id)
            ON DELETE CASCADE
);

-- Index for faster lookups by store
CREATE INDEX idx_menu_items_store_id
    ON menu_items (store_id);